"""Add attachment and images fields to announcement

Revision ID: 25ea4c46be71
Revises: c4433b13e9f0
Create Date: 2026-04-08 20:37:56.244720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ea4c46be71'
down_revision = 'c4433b13e9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_file', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('images')
        batch_op.drop_column('attachment_type')
        batch_op.drop_column('attachment_size')
        batch_op.drop_column('attachment_filename')
        batch_op.drop_column('attachment_file')

    # ### end Alembic commands ###
