"""Add material_links and abele_links tables

Revision ID: b5384a68d8ec
Revises: be78d8765dc4
Create Date: 2026-04-16 22:23:03.994942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5384a68d8ec'
down_revision = 'be78d8765dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('material_title', sa.String(length=300), nullable=False),
    sa.Column('link_name', sa.String(length=100), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reviewer_link')
    with op.batch_alter_table('abele_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['section_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abele_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('color')

    op.create_table('reviewer_link',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('material_title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('link_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('link_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('link_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('material_link')
    # ### end Alembic commands ###
