#!/usr/bin/env python3
import os
import sys

# Add the app directory to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from app import create_app, db
from app.models import Topic, Question

app = create_app()

def init_db():
    """Initialize the database with sample data"""
    with app.app_context():
        # Clear existing data
        db.drop_all()
        db.create_all()
        
        # Create topics
        topics_data = [
            {"name": "Philippine Agricultural Engineering Standards (PAES)", "description": "Standards and specifications for agricultural machinery and structures"},
            {"name": "Irrigation, Soil & Water Management", "description": "Principles and practices of water management for agriculture"},
            {"name": "Farm Power & Machinery", "description": "Agricultural machinery, equipment, and power systems"},
            {"name": "Post-Harvest Technology", "description": "Technologies for handling, processing, and storing agricultural products"},
            {"name": "Environmental Engineering", "description": "Environmental protection and pollution control in agriculture"},
            {"name": "Engineering Economics", "description": "Economic analysis and decision-making for engineering projects"}
        ]
        
        topics = []
        for topic_data in topics_data:
            topic = Topic(**topic_data)
            db.session.add(topic)
            topics.append(topic)
        
        db.session.commit()
        
        # Create questions for each topic
        questions_data = [
    # Topic 1: PAES Questions (1-20)
    {"topic_id": 1, "question_text": "What does PAES stand for?", "option_a": "Philippine Agricultural Extension Services", "option_b": "Philippine Agricultural Engineering Standards", "option_c": "Philippine Agro-Engineering Society", "option_d": "Philippine Agricultural Economic Standards", "correct_answer": "B", "explanation": "PAES stands for Philippine Agricultural Engineering Standards."},
    {"topic_id": 1, "question_text": "Which government agency spearheads the development of PAES?", "option_a": "NEDA", "option_b": "DOST", "option_c": "DA-BAFE", "option_d": "CHED", "correct_answer": "C", "explanation": "DA-BAFE (Department of Agriculture - Bureau of Agricultural and Fisheries Engineering) spearheads PAES development."},
    {"topic_id": 1, "question_text": "What is the main purpose of PAES?", "option_a": "To increase crop production only", "option_b": "To set minimum requirements for agricultural machines and structures", "option_c": "To promote export of local machinery", "option_d": "To replace ISO standards in the Philippines", "correct_answer": "B", "explanation": "PAES sets the minimum quality and safety requirements for agricultural machinery, structures, and post-harvest facilities."},
    {"topic_id": 1, "question_text": "PAES is aligned with which international standards?", "option_a": "ISO", "option_b": "ASTM", "option_c": "IEC", "option_d": "NIST", "correct_answer": "A", "explanation": "PAES is harmonized with International Organization for Standardization (ISO) standards to ensure global compatibility."},
    {"topic_id": 1, "question_text": "Which PAES covers rice mill specifications?", "option_a": "PAES 101", "option_b": "PAES 206", "option_c": "PAES 138", "option_d": "PAES 214", "correct_answer": "B", "explanation": "PAES 206 specifies the requirements and test methods for rice mills."},
    {"topic_id": 1, "question_text": "PAES 110 refers to:", "option_a": "Agricultural tractor – specifications", "option_b": "Four-wheel tractor – methods of test", "option_c": "Hand tractor – methods of test", "option_d": "Corn mill – specifications", "correct_answer": "A", "explanation": "PAES 110 provides the specifications for agricultural tractors."},
    {"topic_id": 1, "question_text": "PAES standards are usually identified by:", "option_a": "Section number only", "option_b": "Year of approval only", "option_c": "Number and year", "option_d": "Color coding", "correct_answer": "C", "explanation": "PAES standards are cited by their number followed by the year of publication (e.g., PAES 101:2000)."},
    {"topic_id": 1, "question_text": "Which PAES standard covers guidelines for designing farm structures like storage?", "option_a": "PAES 401", "option_b": "PAES 214", "option_c": "PAES 218", "option_d": "PAES 101", "correct_answer": "C", "explanation": "PAES 218 provides guidelines for the design of farm structures, including storage facilities."},
    {"topic_id": 1, "question_text": "PAES 218:2017 refers to:", "option_a": "Four-wheel tractor – methods of test", "option_b": "Guidelines on estimating crop production losses", "option_c": "Design of concrete pavement for farm-to-market roads", "option_d": "Small farm reservoir specifications", "correct_answer": "C", "explanation": "PAES 218:2017 specifically covers the design of concrete pavement for farm-to-market roads."},
    {"topic_id": 1, "question_text": "Why are PAES important for engineers?", "option_a": "They serve as a legal basis for project design and implementation", "option_b": "They are optional guidelines only", "option_c": "They are for academic purposes only", "option_d": "They apply only to private farms", "correct_answer": "A", "explanation": "PAES provides the mandatory technical regulations and standards that serve as a legal basis for engineering design and implementation in Philippine agriculture."},
    {"topic_id": 1, "question_text": "PAES are updated every:", "option_a": "3–5 years", "option_b": "10 years", "option_c": "2 years", "option_d": "Whenever needed", "correct_answer": "A", "explanation": "Standards are typically reviewed and updated every 3 to 5 years to incorporate new technologies and address emerging needs."},
    {"topic_id": 1, "question_text": "Which PAES refers to 'Four-Wheel Tractor – Methods of Test'?", "option_a": "PAES 101", "option_b": "PAES 118", "option_c": "PAES 214", "option_d": "PAES 218", "correct_answer": "D", "explanation": "PAES 218 specifies the methods of test for four-wheel tractors."},
    {"topic_id": 1, "question_text": "Which of the following is NOT covered by PAES?", "option_a": "Farm machinery", "option_b": "Soil classification", "option_c": "Post-harvest facilities", "option_d": "Irrigation structures", "correct_answer": "B", "explanation": "Soil classification falls under soil science and is typically covered by other standards or guidelines, not PAES which focuses on engineering aspects."},
    {"topic_id": 1, "question_text": "PAES contributes to which Sustainable Development Goal (SDG)?", "option_a": "Quality education", "option_b": "Zero hunger", "option_c": "Affordable clean energy", "option_d": "Climate action", "correct_answer": "B", "explanation": "By ensuring efficient, reliable, and safe agricultural machinery and infrastructure, PAES helps improve productivity and contributes to food security (Zero Hunger)."},
    {"topic_id": 1, "question_text": "Which office ensures enforcement of PAES in the Philippines?", "option_a": "DA-BAFE", "option_b": "DTI-BPS", "option_c": "DENR", "option_d": "DA-BAR", "correct_answer": "A", "explanation": "The Department of Agriculture - Bureau of Agricultural and Fisheries Engineering (DA-BAFE) is responsible for the development and enforcement of PAES."},
    {"topic_id": 1, "question_text": "PAES 101:2000 refers to:", "option_a": "Agricultural tractor – specifications", "option_b": "Rice thresher – methods of test", "option_c": "Corn sheller – specifications", "option_d": "Hand tractor – methods of test", "correct_answer": "A", "explanation": "PAES 101:2000 provides the specifications for agricultural tractors."},
    {"topic_id": 1, "question_text": "The minimum drawbar power requirement of a four-wheel tractor is specified under:", "option_a": "PAES 118", "option_b": "PAES 101", "option_c": "PAES 214", "option_d": "PAES 218", "correct_answer": "C", "explanation": "PAES 214 covers the testing methods for agricultural tractors, including drawbar performance."},
    {"topic_id": 1, "question_text": "PAES are helpful in protecting farmers because they:", "option_a": "Ensure machines are safe, reliable, and efficient", "option_b": "Give free machines to farmers", "option_c": "Reduce the price of farm inputs", "option_d": "Eliminate need for maintenance", "correct_answer": "A", "explanation": "PAES protects farmers and consumers by ensuring that agricultural machinery and infrastructure meet minimum safety, performance, and quality requirements."},
    {"topic_id": 1, "question_text": "Which PAES is used for moisture meters?", "option_a": "PAES 214", "option_b": "PAES 103", "option_c": "PAES 138", "option_d": "PAES 119", "correct_answer": "C", "explanation": "PAES 138 provides the specifications and test methods for moisture meters used for grains and other agricultural products."},
    {"topic_id": 1, "question_text": "The PAES standard number usually consists of:", "option_a": "2 digits only", "option_b": "Title + year", "option_c": "Number + year", "option_d": "Section only", "correct_answer": "C", "explanation": "A PAES standard is uniquely identified by its number followed by the year of publication (e.g., PAES 101:2000)."},

    # Topic 2: Irrigation, Soil & Water Management Questions (21-40)
    {"topic_id": 2, "question_text": "Which is the main purpose of irrigation?", "option_a": "To supply nutrients to crops", "option_b": "To provide artificial water supply to crops", "option_c": "To protect plants from pests", "option_d": "To increase soil fertility", "correct_answer": "B", "explanation": "Irrigation is the artificial application of water to soil to assist in growing crops."},
    {"topic_id": 2, "question_text": "Which type of irrigation system uses pipes, emitters, and low discharge rates?", "option_a": "Sprinkler irrigation", "option_b": "Drip irrigation", "option_c": "Surface irrigation", "option_d": "Flood irrigation", "correct_answer": "B", "explanation": "Drip irrigation delivers water directly to the root zone of plants through a network of pipes and emitters at a low flow rate."},
    {"topic_id": 2, "question_text": "The process of supplying water to soil by allowing it to flow over the field surface is called:", "option_a": "Sprinkler irrigation", "option_b": "Surface irrigation", "option_c": "Drip irrigation", "option_d": "Subsurface irrigation", "correct_answer": "B", "explanation": "Surface irrigation involves water flowing over the soil surface by gravity to wet and infiltrate into the soil."},
    {"topic_id": 2, "question_text": "The depth of water required to raise the soil moisture to field capacity is known as:", "option_a": "Wilting point", "option_b": "Irrigation requirement", "option_c": "Net irrigation depth", "option_d": "Consumptive use", "correct_answer": "C", "explanation": "Net irrigation depth is the depth of water needed to refill the root zone from its current moisture level to field capacity."},
    {"topic_id": 2, "question_text": "Which soil texture has the highest water holding capacity?", "option_a": "Sand", "option_b": "Clay", "option_c": "Silt loam", "option_d": "Gravel", "correct_answer": "B", "explanation": "Clay soils have the smallest particle size and largest surface area, allowing them to hold more water against gravity than sand or silt."},
    {"topic_id": 2, "question_text": "The ratio of the volume of water beneficially used to the volume of water delivered is called:", "option_a": "Conveyance efficiency", "option_b": "Application efficiency", "option_c": "Irrigation efficiency", "option_d": "Storage efficiency", "correct_answer": "C", "explanation": "Irrigation efficiency is a general term for the effectiveness of an irrigation system in delivering water for crop use, often encompassing conveyance and application efficiency."},
    {"topic_id": 2, "question_text": "Which irrigation method is most suitable for rice fields?", "option_a": "Furrow irrigation", "option_b": "Flood irrigation", "option_c": "Basin irrigation", "option_d": "Drip irrigation", "correct_answer": "B", "explanation": "Flood irrigation, where the field is submerged, is the traditional and most common method for rice cultivation as it mimics the crop's natural growing conditions."},
    {"topic_id": 2, "question_text": "The movement of water into the soil surface is called:", "option_a": "Percolation", "option_b": "Infiltration", "option_c": "Evapotranspiration", "option_d": "Capillary rise", "correct_answer": "B", "explanation": "Infiltration is the process by which water on the ground surface enters the soil."},
    {"topic_id": 2, "question_text": "The downward movement of water through the soil profile beyond the root zone is:", "option_a": "Capillary rise", "option_b": "Runoff", "option_c": "Percolation", "option_d": "Infiltration", "correct_answer": "C", "explanation": "Percolation is the downward movement of water through soil layers, often beyond the reach of plant roots, potentially recharging groundwater."},
    {"topic_id": 2, "question_text": "Which instrument is commonly used to measure soil moisture tension?", "option_a": "Psychrometer", "option_b": "Thermometer", "option_c": "Tensiometer", "option_d": "Hygrometer", "correct_answer": "C", "explanation": "A tensiometer measures the soil moisture tension, which indicates how hard plants must work to extract water from the soil."},
    {"topic_id": 2, "question_text": "Field capacity of soil refers to:", "option_a": "Maximum water soil can hold by gravity", "option_b": "Water retained in soil after excess drains away", "option_c": "Minimum soil water for plant survival", "option_d": "Water content at wilting point", "correct_answer": "B", "explanation": "Field capacity is the amount of water remaining in a soil after it has been saturated and allowed to drain freely for a day or two."},
    {"topic_id": 2, "question_text": "The total water required for crop growth including losses is called:", "option_a": "Net irrigation requirement", "option_b": "Consumptive use", "option_c": "Duty of water", "option_d": "Effective rainfall", "correct_answer": "B", "explanation": "Consumptive use (or evapotranspiration) is the total water used by the crop for transpiration and building tissue, plus water evaporated from the soil surface."},
    {"topic_id": 2, "question_text": "The ratio of irrigated area to the quantity of water supplied is expressed as:", "option_a": "Water requirement", "option_b": "Duty of water", "option_c": "Delta", "option_d": "Irrigation efficiency", "correct_answer": "B", "explanation": "Duty of water is the area of land that can be irrigated with a unit volume of water (e.g., hectares per cubic meter per second)."},
    {"topic_id": 2, "question_text": "Which method of irrigation is most water-efficient?", "option_a": "Drip irrigation", "option_b": "Sprinkler irrigation", "option_c": "Surface irrigation", "option_d": "Flood irrigation", "correct_answer": "A", "explanation": "Drip irrigation is highly efficient as it applies water directly to the root zone, minimizing evaporation, runoff, and deep percolation losses."},
    {"topic_id": 2, "question_text": "The moisture content at which plants can no longer extract water is called:", "option_a": "Field capacity", "option_b": "Hygroscopic water", "option_c": "Permanent wilting point", "option_d": "Capillary water", "correct_answer": "C", "explanation": "Permanent wilting point is the soil moisture content at which plants wilt and cannot recover even if water is added."},
    {"topic_id": 2, "question_text": "Which type of soil allows the fastest infiltration?", "option_a": "Sandy soil", "option_b": "Clay soil", "option_c": "Loam soil", "option_d": "Silt soil", "correct_answer": "A", "explanation": "Sandy soils have large pores, allowing water to infiltrate rapidly compared to clay soils with small pores."},
    {"topic_id": 2, "question_text": "Which factor does NOT directly affect irrigation scheduling?", "option_a": "Crop type", "option_b": "Rainfall", "option_c": "Soil texture", "option_d": "Color of soil", "correct_answer": "D", "explanation": "While soil color can indicate organic matter, it is not a direct hydraulic property used for calculating irrigation timing or depth. Crop type, rainfall, and soil texture are critical inputs."},
    {"topic_id": 2, "question_text": "The combination of evaporation from soil and transpiration from plants is called:", "option_a": "Percolation", "option_b": "Capillarity", "option_c": "Evapotranspiration", "option_d": "Consumptive irrigation", "correct_answer": "C", "explanation": "Evapotranspiration (ET) is the combined loss of water from the soil surface (evaporation) and from the plant (transpiration)."},
    {"topic_id": 2, "question_text": "Which irrigation method simulates rainfall?", "option_a": "Surface irrigation", "option_b": "Sprinkler irrigation", "option_c": "Drip irrigation", "option_d": "Furrow irrigation", "correct_answer": "B", "explanation": "Sprinkler irrigation distributes water through the air via a system of pipes and pumps, simulating natural rainfall."},
    {"topic_id": 2, "question_text": "Which water property is essential for capillary rise in soils?", "option_a": "Cohesion", "option_b": "Adhesion", "option_c": "Surface tension", "option_d": "All of the above", "correct_answer": "D", "explanation": "Capillary rise is caused by the combined effects of adhesion (water sticking to soil particles), cohesion (water molecules sticking to each other), and surface tension."},

    # Topic 3: Farm Power & Machinery Questions (41-60)
    {"topic_id": 3, "question_text": "The most common source of farm power in the Philippines is:", "option_a": "Human power", "option_b": "Animal power", "option_c": "Tractor power", "option_d": "Solar power", "correct_answer": "A", "explanation": "Human labor remains the most prevalent source of power for many small-scale farming operations in the Philippines."},
    {"topic_id": 3, "question_text": "A two-wheeled power unit used for plowing and tilling is called:", "option_a": "Four-wheel tractor", "option_b": "Hand tractor", "option_c": "Garden cultivator", "option_d": "Rotary tiller", "correct_answer": "B", "explanation": "A hand tractor, or walking-type tractor, is a common two-wheeled prime mover in Philippine agriculture."},
    {"topic_id": 3, "question_text": "The pulling capacity of a tractor is usually expressed as:", "option_a": "Brake horsepower", "option_b": "Drawbar horsepower", "option_c": "Axle load", "option_d": "Flywheel power", "correct_answer": "B", "explanation": "Drawbar horsepower (dbhp) measures the power available at the tractor's drawbar to pull implements, indicating its actual pulling capability."},
    {"topic_id": 3, "question_text": "PTO in tractors stands for:", "option_a": "Power Torque Output", "option_b": "Power Take-Off", "option_c": "Pulling Tractor Operation", "option_d": "Power Transmission Output", "correct_answer": "B", "explanation": "PTO (Power Take-Off) is a driveshaft that transfers power from the tractor to attached implements."},
    {"topic_id": 3, "question_text": "Which machine is used to separate grain from straw?", "option_a": "Rice mill", "option_b": "Corn sheller", "option_c": "Thresher", "option_d": "Harvester", "correct_answer": "C", "explanation": "A thresher is specifically designed to separate grains from their stalks or husks."},
    {"topic_id": 3, "question_text": "The device in a tractor that allows the operator to lift or lower implements is:", "option_a": "PTO shaft", "option_b": "Hydraulic system", "option_c": "Drawbar", "option_d": "Gearbox", "correct_answer": "B", "explanation": "The hydraulic system provides the force needed to raise and lower implements attached to the tractor."},
    {"topic_id": 3, "question_text": "A machine used for land leveling in the field is called:", "option_a": "Harrow", "option_b": "Plow", "option_c": "Blade leveler", "option_d": "Ridger", "correct_answer": "C", "explanation": "A blade leveler or land leveler is specifically designed to create a uniform, level surface for irrigation and planting."},
    {"topic_id": 3, "question_text": "The part of a moldboard plow that cuts the soil horizontally is called:", "option_a": "Share", "option_b": "Moldboard", "option_c": "Landside", "option_d": "Beam", "correct_answer": "A", "explanation": "The share is the cutting component of a plow that slices through the soil horizontally."},
    {"topic_id": 3, "question_text": "The efficiency of a field operation is reduced mainly due to:", "option_a": "High horsepower", "option_b": "Fuel efficiency", "option_c": "Turning losses and overlaps", "option_d": "Soil fertility", "correct_answer": "C", "explanation": "Field efficiency decreases due to time spent turning at field ends and potential overlaps or gaps in coverage."},
    {"topic_id": 3, "question_text": "Which of the following is a primary tillage implement?", "option_a": "Disc harrow", "option_b": "Moldboard plow", "option_c": "Rotary hoe", "option_d": "Spike-tooth harrow", "correct_answer": "B", "explanation": "A moldboard plow is used for primary tillage, which is the initial major soil working operation."},
    {"topic_id": 3, "question_text": "The speed ratio between the engine and PTO shaft is generally:", "option_a": "540 or 1000 rpm", "option_b": "720 rpm", "option_c": "1200 rpm", "option_d": "1800 rpm", "correct_answer": "A", "explanation": "Standard PTO speeds are 540 rpm for smaller implements and 1000 rpm for larger, higher-capacity equipment."},
    {"topic_id": 3, "question_text": "The type of thresher that uses axial flow is commonly used for:", "option_a": "Rice", "option_b": "Corn", "option_c": "Sorghum", "option_d": "Soybean", "correct_answer": "A", "explanation": "Axial flow threshers are particularly effective for rice as they provide gentle threshing action that minimizes grain damage."},
    {"topic_id": 3, "question_text": "A disc plow is more suitable than a moldboard plow in:", "option_a": "Sandy soil", "option_b": "Rocky soil", "option_c": "Loam soil", "option_d": "Clay soil", "correct_answer": "B", "explanation": "Disc plows are better suited for rocky or hard soil conditions where a moldboard plow might get stuck or damaged."},
    {"topic_id": 3, "question_text": "The unit of engine power is expressed in:", "option_a": "Newton", "option_b": "Joule", "option_c": "Watt or horsepower", "option_d": "Pascal", "correct_answer": "C", "explanation": "Engine power is typically measured in watts (metric) or horsepower (imperial system)."},
    {"topic_id": 3, "question_text": "The part of the combine harvester that separates grain from straw is the:", "option_a": "Header", "option_b": "Reel", "option_c": "Threshing cylinder", "option_d": "Cutter bar", "correct_answer": "C", "explanation": "The threshing cylinder is the component that separates the grain from the straw through impact and rubbing action."},
    {"topic_id": 3, "question_text": "A walking-type tractor is commonly known as:", "option_a": "Power cultivator", "option_b": "Hand tractor", "option_c": "Garden tractor", "option_d": "Mini tractor", "correct_answer": "B", "explanation": "Hand tractor is the common term for a two-wheeled walking-type tractor used in small-scale farming."},
    {"topic_id": 3, "question_text": "The effective field capacity (EFC) of a machine depends on:", "option_a": "Engine horsepower only", "option_b": "Theoretical field capacity and field efficiency", "option_c": "Soil moisture only", "option_d": "Fuel type", "correct_answer": "B", "explanation": "Effective field capacity is calculated as theoretical capacity multiplied by field efficiency, which accounts for turning time and other operational factors."},
    {"topic_id": 3, "question_text": "Which type of harrow is commonly used after plowing to break clods?", "option_a": "Disc harrow", "option_b": "Spike-tooth harrow", "option_c": "Chain harrow", "option_d": "Spring-tooth harrow", "correct_answer": "A", "explanation": "Disc harrows are particularly effective at breaking up clods and preparing seedbeds after primary tillage."},
    {"topic_id": 3, "question_text": "A reaper is primarily used for:", "option_a": "Planting seeds", "option_b": "Harvesting standing crops", "option_c": "Milling grains", "option_d": "Drying crops", "correct_answer": "B", "explanation": "A reaper is a harvesting machine that cuts standing crops and may lay them in swaths for further processing."},
    {"topic_id": 3, "question_text": "The fuel commonly used in agricultural tractors is:", "option_a": "Gasoline", "option_b": "Diesel", "option_c": "Kerosene", "option_d": "Ethanol", "correct_answer": "B", "explanation": "Diesel fuel is most commonly used in agricultural tractors due to its higher energy density and better fuel efficiency."},

    # Topic 4: Post-Harvest Technology Questions (61-80)
    {"topic_id": 4, "question_text": "What does post-harvest technology mainly deal with?", "option_a": "Soil fertility", "option_b": "Handling and processing crops after harvest", "option_c": "Crop irrigation", "option_d": "Farm mechanization", "correct_answer": "B", "explanation": "Post-harvest technology focuses on preserving, processing, packaging, storing, and transporting agricultural products after harvest."},
    {"topic_id": 4, "question_text": "The main purpose of drying grains is to:", "option_a": "Improve taste", "option_b": "Reduce bulk", "option_c": "Prevent spoilage by lowering moisture", "option_d": "Increase weight", "correct_answer": "C", "explanation": "Drying reduces moisture content to safe levels that prevent microbial growth and spoilage during storage."},
    {"topic_id": 4, "question_text": "The recommended safe moisture content for storing rice is about:", "option_a": "24%", "option_b": "18%", "option_c": "14%", "option_d": "10%", "correct_answer": "C", "explanation": "14% moisture content is generally considered safe for long-term storage of rice to prevent mold growth and insect infestation."},
    {"topic_id": 4, "question_text": "The process of separating grain from chaff is called:", "option_a": "Milling", "option_b": "Threshing", "option_c": "Winnowing", "option_d": "Grinding", "correct_answer": "C", "explanation": "Winnowing is the process of separating lighter chaff from heavier grains using air currents."},
    {"topic_id": 4, "question_text": "In rice milling, the removal of husk from paddy is called:", "option_a": "Whitening", "option_b": "Polishing", "option_c": "Dehusking", "option_d": "Grading", "correct_answer": "C", "explanation": "Dehusking or dehulling is the process of removing the outer husk from paddy rice."},
    {"topic_id": 4, "question_text": "The test weight of grains is usually expressed in:", "option_a": "Kilograms per liter", "option_b": "Kilograms per cubic meter", "option_c": "Kilograms per hectare", "option_d": "Kilograms per sack", "correct_answer": "B", "explanation": "Test weight is a measure of grain density typically expressed as mass per unit volume (kg/m³)."},
    {"topic_id": 4, "question_text": "The most critical factor affecting storage life of grains is:", "option_a": "Temperature", "option_b": "Moisture content", "option_c": "Packaging material", "option_d": "Grain size", "correct_answer": "B", "explanation": "Moisture content is the primary factor determining storage life, as it affects microbial growth, insect activity, and biochemical changes."},
    {"topic_id": 4, "question_text": "Which machine is used to remove stones and impurities from grains?", "option_a": "Destoner", "option_b": "Sheller", "option_c": "Separator", "option_d": "Cleaner", "correct_answer": "A", "explanation": "A destoner is specifically designed to remove stones, dirt, and other heavy impurities from grains based on density differences."},
    {"topic_id": 4, "question_text": "The term 'head rice' refers to:", "option_a": "Whole kernels of rice after milling", "option_b": "Broken rice grains", "option_c": "Partially milled rice", "option_d": "Rice bran", "correct_answer": "A", "explanation": "Head rice consists of whole, unbroken milled rice kernels, which command a higher market price than broken grains."},
    {"topic_id": 4, "question_text": "A flatbed dryer operates mainly by:", "option_a": "Sunlight heating", "option_b": "Heated air blown through grain layers", "option_c": "Vacuum drying", "option_d": "Radiation drying", "correct_answer": "B", "explanation": "Flatbed dryers use forced convection where heated air is blown through a stationary layer of grains to remove moisture."},
    {"topic_id": 4, "question_text": "In post-harvest handling, 'spoilage organisms' usually include:", "option_a": "Insects and rodents only", "option_b": "Fungi, bacteria, insects, and rodents", "option_c": "Nutrients in the grain", "option_d": "None of the above", "correct_answer": "B", "explanation": "Spoilage organisms encompass a wide range of biological agents including microorganisms (fungi, bacteria) and pests (insects, rodents)."},
    {"topic_id": 4, "question_text": "Mechanical drying is generally preferred over sun drying because it is:", "option_a": "Faster and more controlled", "option_b": "Always cheaper", "option_c": "Easier to do in large fields", "option_d": "Unaffected by grain moisture", "correct_answer": "A", "explanation": "Mechanical drying offers faster, more consistent, and controllable drying conditions regardless of weather."},
    {"topic_id": 4, "question_text": "Rice milling recovery is defined as the percentage of:", "option_a": "Head rice to total paddy", "option_b": "Milled rice to total paddy", "option_c": "Husk to total paddy", "option_d": "Bran to total paddy", "correct_answer": "B", "explanation": "Milling recovery is the weight percentage of milled rice obtained from the original paddy."},
    {"topic_id": 4, "question_text": "Hermetic storage technology prevents:", "option_a": "Water seepage only", "option_b": "Entry of air and insects", "option_c": "Overheating of grains", "option_d": "Reduction of grain size", "correct_answer": "B", "explanation": "Hermetic storage creates an airtight environment that prevents oxygen entry and controls insects through modified atmosphere."},
    {"topic_id": 4, "question_text": "A solar grain dryer uses:", "option_a": "Direct sunlight exposure only", "option_b": "Solar energy with collector and airflow system", "option_c": "Electric heaters", "option_d": "Fuel-powered burners", "correct_answer": "B", "explanation": "Solar dryers typically use solar collectors to heat air, which is then circulated through the grain by natural or forced convection."},
    {"topic_id": 4, "question_text": "The by-product of rice milling that is used for animal feed is:", "option_a": "Rice husk", "option_b": "Rice bran", "option_c": "Broken rice", "option_d": "Head rice", "correct_answer": "B", "explanation": "Rice bran is a nutritious by-product of milling that is commonly used as animal feed due to its high protein and fat content."},
    {"topic_id": 4, "question_text": "The allowable percentage of broken grains in good quality milled rice is usually around:", "option_a": "5%", "option_b": "10%", "option_c": "25%", "option_d": "50%", "correct_answer": "B", "explanation": "Premium quality milled rice typically contains no more than 10% broken grains."},
    {"topic_id": 4, "question_text": "A corn sheller is primarily used for:", "option_a": "Removing husk of corn", "option_b": "Separating kernels from the cob", "option_c": "Grinding corn into flour", "option_d": "Cleaning corn kernels", "correct_answer": "B", "explanation": "A corn sheller is designed specifically to remove kernels from the cob without damaging them."},
    {"topic_id": 4, "question_text": "The main cause of aflatoxin contamination in grains is:", "option_a": "High protein content", "option_b": "Fungal growth under moist conditions", "option_c": "Insect feeding", "option_d": "Sunlight exposure", "correct_answer": "B", "explanation": "Aflatoxins are toxic compounds produced by certain molds (Aspergillus species) that grow on grains stored under warm, humid conditions."},
    {"topic_id": 4, "question_text": "Controlled atmosphere storage regulates:", "option_a": "Oxygen and carbon dioxide levels", "option_b": "Grain temperature only", "option_c": "Soil moisture", "option_d": "Fertilizer levels", "correct_answer": "A", "explanation": "Controlled atmosphere storage modifies the composition of gases (typically reducing oxygen and increasing carbon dioxide) to extend storage life and control pests."},

    # Topic 5: Environmental Engineering Questions (81-100)
    {"topic_id": 5, "question_text": "Environmental engineering mainly deals with:", "option_a": "Construction of highways", "option_b": "Protection of natural resources and pollution control", "option_c": "Designing farm machinery", "option_d": "Increasing crop yields only", "correct_answer": "B", "explanation": "Environmental engineering focuses on protecting human health and the environment through waste management, pollution control, and resource conservation."},
    {"topic_id": 5, "question_text": "The process of converting organic waste into useful soil conditioner is called:", "option_a": "Recycling", "option_b": "Composting", "option_c": "Incineration", "option_d": "Digestion", "correct_answer": "B", "explanation": "Composting is the controlled biological decomposition of organic materials into a stable, humus-like product that improves soil quality."},
    {"topic_id": 5, "question_text": "Which greenhouse gas has the highest global warming potential (GWP)?", "option_a": "Carbon dioxide (CO₂)", "option_b": "Methane (CH₄)", "option_c": "Nitrous oxide (N₂O)", "option_d": "Chlorofluorocarbons (CFCs)", "correct_answer": "D", "explanation": "CFCs have extremely high global warming potential, thousands of times greater than CO₂, though they're present in much smaller quantities."},
    {"topic_id": 5, "question_text": "Septic tanks are used for:", "option_a": "Treating solid waste", "option_b": "Treating domestic wastewater", "option_c": "Disposing of hazardous waste", "option_d": "Recycling plastics", "correct_answer": "B", "explanation": "Septic tanks are underground wastewater treatment systems that use natural processes to treat household sewage."},
    {"topic_id": 5, "question_text": "The law in the Philippines that promotes ecological solid waste management is:", "option_a": "RA 8749", "option_b": "RA 9275", "option_c": "RA 9003", "option_d": "RA 7586", "correct_answer": "C", "explanation": "Republic Act 9003, also known as the Ecological Solid Waste Management Act of 2000, provides the legal framework for waste management in the Philippines."},
    {"topic_id": 5, "question_text": "The main purpose of wastewater treatment is to:", "option_a": "Remove harmful contaminants before disposal or reuse", "option_b": "Increase the volume of water", "option_c": "Produce drinking water directly", "option_d": "Reduce soil erosion", "correct_answer": "A", "explanation": "Wastewater treatment removes physical, chemical, and biological contaminants to protect public health and the environment."},
    {"topic_id": 5, "question_text": "The layer of atmosphere that protects us from UV radiation is:", "option_a": "Troposphere", "option_b": "Stratosphere", "option_c": "Mesosphere", "option_d": "Exosphere", "correct_answer": "B", "explanation": "The stratosphere contains the ozone layer, which absorbs most of the sun's harmful ultraviolet radiation."},
    {"topic_id": 5, "question_text": "Which type of renewable energy uses moving water to generate electricity?", "option_a": "Solar power", "option_b": "Wind power", "option_c": "Hydropower", "option_d": "Biomass power", "correct_answer": "C", "explanation": "Hydropower converts the energy of flowing or falling water into electricity through turbines and generators."},
    {"topic_id": 5, "question_text": "The pH range of water considered safe for drinking is approximately:", "option_a": "3–5", "option_b": "5–6", "option_c": "6.5–8.5", "option_d": "9–11", "correct_answer": "C", "explanation": "Drinking water should have a pH between 6.5 and 8.5 to be safe for consumption and to prevent corrosion or scaling in pipes."},
    {"topic_id": 5, "question_text": "Which solid waste disposal method reduces volume but may cause air pollution?", "option_a": "Composting", "option_b": "Recycling", "option_c": "Incineration", "option_d": "Landfilling", "correct_answer": "C", "explanation": "Incineration reduces waste volume by up to 90% but can produce air pollutants if not properly controlled with emission treatment systems."},
    {"topic_id": 5, "question_text": "The main pollutant responsible for acid rain is:", "option_a": "Carbon monoxide (CO)", "option_b": "Sulfur dioxide (SO₂)", "option_c": "Methane (CH₄)", "option_d": "Nitrogen gas (N₂)", "correct_answer": "B", "explanation": "Sulfur dioxide emissions from industrial processes and fossil fuel combustion are the primary cause of acid rain."},
    {"topic_id": 5, "question_text": "A constructed wetland is designed mainly for:", "option_a": "Flood control", "option_b": "Wildlife conservation", "option_c": "Wastewater treatment", "option_d": "Irrigation storage", "correct_answer": "C", "explanation": "Constructed wetlands use natural processes involving wetland vegetation, soils, and their associated microbial assemblages to treat wastewater."},
    {"topic_id": 5, "question_text": "The Philippine Clean Air Act is officially known as:", "option_a": "RA 9275", "option_b": "RA 8749", "option_c": "RA 9003", "option_d": "RA 10068", "correct_answer": "B", "explanation": "Republic Act 8749, the Philippine Clean Air Act, provides a comprehensive air quality management policy and program."},
    {"topic_id": 5, "question_text": "Which of the following is considered a non-renewable energy resource?", "option_a": "Solar energy", "option_b": "Wind energy", "option_c": "Coal", "option_d": "Hydropower", "correct_answer": "C", "explanation": "Coal is a fossil fuel that takes millions of years to form, making it non-renewable on human timescales."},
    {"topic_id": 5, "question_text": "The main purpose of sedimentation in water treatment is to:", "option_a": "Kill bacteria", "option_b": "Remove suspended solids", "option_c": "Remove dissolved gases", "option_d": "Reduce hardness", "correct_answer": "B", "explanation": "Sedimentation allows heavier suspended particles to settle out of water by gravity before further treatment."},
    {"topic_id": 5, "question_text": "Which greenhouse gas is primarily released from flooded rice fields?", "option_a": "Methane (CH₄)", "option_b": "Nitrous oxide (N₂O)", "option_c": "Carbon dioxide (CO₂)", "option_d": "Ammonia (NH₃)", "correct_answer": "A", "explanation": "Flooded rice fields create anaerobic conditions that promote methane production by methanogenic bacteria."},
    {"topic_id": 5, "question_text": "A biogas digester primarily produces:", "option_a": "Carbon dioxide", "option_b": "Methane", "option_c": "Nitrogen", "option_d": "Oxygen", "correct_answer": "B", "explanation": "Biogas digesters use anaerobic digestion to break down organic matter, producing methane-rich biogas as a primary product."},
    {"topic_id": 5, "question_text": "Which waste management method involves reuse of materials to make new products?", "option_a": "Composting", "option_b": "Recycling", "option_c": "Landfilling", "option_d": "Incineration", "correct_answer": "B", "explanation": "Recycling involves processing used materials into new products, reducing the consumption of fresh raw materials."},
    {"topic_id": 5, "question_text": "The Philippine Clean Water Act is known as:", "option_a": "RA 8749", "option_b": "RA 9275", "option_c": "RA 9003", "option_d": "RA 10068", "correct_answer": "B", "explanation": "Republic Act 9275, the Philippine Clean Water Act, aims to protect the country's water bodies from pollution."},
    {"topic_id": 5, "question_text": "Which is the most environmentally friendly hierarchy of waste management?", "option_a": "Landfill → Incineration → Recycling → Reuse", "option_b": "Reuse → Recycling → Reduce → Disposal", "option_c": "Reduce → Reuse → Recycling → Disposal", "option_d": "Recycling → Reduce → Disposal → Composting", "correct_answer": "C", "explanation": "The waste hierarchy prioritizes waste prevention (reduce) as most preferred, followed by reuse, recycling, recovery, with disposal as last resort."},

    # Topic 6: Engineering Economics Questions (101-120)
    {"topic_id": 6, "question_text": "Engineering economics is mainly concerned with:", "option_a": "Soil fertility", "option_b": "Economic evaluation of engineering projects", "option_c": "Mechanical design", "option_d": "Crop production", "correct_answer": "B", "explanation": "Engineering economics applies economic principles to the evaluation of engineering design and project alternatives."},
    {"topic_id": 6, "question_text": "The time value of money means:", "option_a": "Money today is worth more than money in the future", "option_b": "Money has no change in value over time", "option_c": "Money in the past has no value", "option_d": "Money loses value instantly", "correct_answer": "A", "explanation": "The time value of money recognizes that money available now is worth more than the same amount in the future due to its potential earning capacity."},
    {"topic_id": 6, "question_text": "The interest earned on both the principal and accumulated interest is called:", "option_a": "Simple interest", "option_b": "Compound interest", "option_c": "Discount rate", "option_d": "Nominal interest", "correct_answer": "B", "explanation": "Compound interest calculates interest on both the initial principal and the accumulated interest from previous periods."},
    {"topic_id": 6, "question_text": "Which formula is used to find the future value (F) of present money (P)?", "option_a": "F = P(1 + i)ⁿ", "option_b": "F = P / (1 + i)ⁿ", "option_c": "F = P – iⁿ", "option_d": "F = P × n × i", "correct_answer": "A", "explanation": "The formula F = P(1 + i)ⁿ calculates the future value of a present sum, where i is the interest rate and n is the number of periods."},
    {"topic_id": 6, "question_text": "The process of finding present value (P) from a future value (F) is called:", "option_a": "Compounding", "option_b": "Discounting", "option_c": "Inflation", "option_d": "Amortization", "correct_answer": "B", "explanation": "Discounting is the process of determining the present value of a future cash flow by applying a discount rate."},
    {"topic_id": 6, "question_text": "The break-even point occurs when:", "option_a": "Total revenue = Total cost", "option_b": "Profit = Maximum", "option_c": "Fixed cost = Variable cost", "option_d": "Revenue = 0", "correct_answer": "A", "explanation": "The break-even point is where total revenue equals total costs, resulting in neither profit nor loss."},
    {"topic_id": 6, "question_text": "Costs that do not change with the level of production are called:", "option_a": "Variable costs", "option_b": "Fixed costs", "option_c": "Marginal costs", "option_d": "Incremental costs", "correct_answer": "B", "explanation": "Fixed costs remain constant regardless of production volume (e.g., rent, insurance, salaries)."},
    {"topic_id": 6, "question_text": "Which of the following is a variable cost in farming?", "option_a": "Land tax", "option_b": "Equipment depreciation", "option_c": "Fuel and labor", "option_d": "Insurance", "correct_answer": "C", "explanation": "Variable costs change with production level; fuel and labor costs increase with more farming activities."},
    {"topic_id": 6, "question_text": "Depreciation is defined as:", "option_a": "Increase in asset value over time", "option_b": "Decrease in asset value over time due to wear and tear", "option_c": "Amount of loan interest", "option_d": "Profit gained per year", "correct_answer": "B", "explanation": "Depreciation is the systematic allocation of an asset's cost over its useful life to account for wear, obsolescence, or deterioration."},
    {"topic_id": 6, "question_text": "Which depreciation method spreads the cost evenly over an asset's life?", "option_a": "Sum-of-years-digits method", "option_b": "Straight-line method", "option_c": "Declining balance method", "option_d": "Double-declining balance method", "correct_answer": "B", "explanation": "The straight-line method allocates equal depreciation expense each year over the asset's useful life."},
    {"topic_id": 6, "question_text": "The rate that makes the present worth of benefits equal to costs is called:", "option_a": "Interest rate", "option_b": "Discount rate", "option_c": "Internal rate of return (IRR)", "option_d": "Break-even rate", "correct_answer": "C", "explanation": "The internal rate of return (IRR) is the discount rate that makes the net present value of all cash flows equal to zero."},
    {"topic_id": 6, "question_text": "The formula for Net Present Value (NPV) is:", "option_a": "NPV = Benefits – Costs (discounted)", "option_b": "NPV = Total revenue – Total fixed costs", "option_c": "NPV = Interest × Time", "option_d": "NPV = Assets – Liabilities", "correct_answer": "A", "explanation": "NPV is calculated as the sum of present values of all cash inflows minus the sum of present values of all cash outflows."},
    {"topic_id": 6, "question_text": "If NPV is positive, the project is:", "option_a": "Not acceptable", "option_b": "Acceptable and profitable", "option_c": "Risky", "option_d": "Always rejected", "correct_answer": "B", "explanation": "A positive NPV indicates that the projected earnings (in present dollars) exceed the anticipated costs, making the project profitable."},
    {"topic_id": 6, "question_text": "Payback period refers to:", "option_a": "Time required to recover investment cost", "option_b": "Time before asset depreciation starts", "option_c": "Time of equipment warranty", "option_d": "Interest repayment schedule", "correct_answer": "A", "explanation": "Payback period is the length of time required to recover the cost of an investment through net cash inflows."},
    {"topic_id": 6, "question_text": "Which is considered a sunk cost?", "option_a": "Cost of fuel for future operation", "option_b": "Original purchase price of used equipment", "option_c": "Wages of seasonal labor", "option_d": "Future investment cost", "correct_answer": "B", "explanation": "A sunk cost is a cost that has already been incurred and cannot be recovered, such as the purchase price of equipment already bought."},
    {"topic_id": 6, "question_text": "Opportunity cost is defined as:", "option_a": "Loss due to depreciation", "option_b": "The value of the next best alternative forgone", "option_c": "Extra income from a project", "option_d": "The amount of variable cost saved", "correct_answer": "B", "explanation": "Opportunity cost represents the benefits you could have received by taking an alternative action."},
    {"topic_id": 6, "question_text": "The market value of a machine after its useful life is called:", "option_a": "Scrap value", "option_b": "Salvage value", "option_c": "Replacement value", "option_d": "Depreciated cost", "correct_answer": "B", "explanation": "Salvage value is the estimated resale value of an asset at the end of its useful life."},
    {"topic_id": 6, "question_text": "If the interest rate is higher, the present value of future cash flows will be:", "option_a": "Higher", "option_b": "Lower", "option_c": "Equal", "option_d": "Unchanged", "correct_answer": "B", "explanation": "Higher discount rates reduce the present value of future cash flows due to increased time value of money considerations."},
    {"topic_id": 6, "question_text": "A cash flow diagram is used to:", "option_a": "Show crop growth stages", "option_b": "Illustrate timing of costs and revenues", "option_c": "Compute soil erosion rate", "option_d": "Record rainfall amounts", "correct_answer": "B", "explanation": "Cash flow diagrams visually represent the timing and magnitude of cash inflows and outflows associated with a project."},
    {"topic_id": 6, "question_text": "Which financial analysis tool compares alternatives based on cost per unit of output?", "option_a": "Cost-benefit ratio", "option_b": "Break-even analysis", "option_c": "Benefit-cost analysis", "option_d": "Cost-effectiveness analysis", "correct_answer": "D", "explanation": "Cost-effectiveness analysis compares alternatives based on their costs relative to their outputs or effects, typically expressed as cost per unit of outcome."}
]
        # Add all 120 questions (6 topics × 20 questions)
        for question_data in questions_data:
            question = Question(**question_data)
            db.session.add(question)
        
        db.session.commit()
        print(f"Added {len(topics_data)} topics and {len(questions_data)} questions to the database.")

    # Add this to your database initialization script
def create_study_sessions_table(conn):
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS study_sessions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER,
            start_time DATETIME,
            end_time DATETIME,
            duration_minutes INTEGER,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users (id)
        )
    ''')
    conn.commit()
    
if __name__ == '__main__':
    print("Initializing database...")
    init_db()
    print("Database initialized successfully!")